group=com.github.einnxk
version=4.2.6

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.warning.mode=all
org.gradle.logging.stacktrace=all
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=fail
org.gradle.kotlin.dsl.allWarningsAsErrors=true
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
