[versions]
lombok = "1.18.46"
gson = "2.14.0"
jetbrains = "26.1.0"
jspecify = "1.0.0"

[libraries]
lombok = {module = "org.projectlombok:lombok", version.ref = "lombok"}
gson = {module = "com.google.code.gson:gson", version.ref = "gson"}
jetbrains = {module = "org.jetbrains:annotations", version.ref = "jetbrains"}
jspecify = {module = "org.jspecify:jspecify", version.ref = "jspecify"}